# Generated by Django 3.1.4 on 2022-09-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GraphsCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={"db_table": "graphs_category", "managed": False,},
        ),
        migrations.CreateModel(
            name="GraphsData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateTimeField(auto_now=True)),
                ("json_data", models.TextField()),
                ("power", models.FloatField()),
            ],
            options={"db_table": "graphs_data", "managed": False,},
        ),
        migrations.CreateModel(
            name="GraphsInstallation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={"db_table": "graphs_installation", "managed": False,},
        ),
    ]
